// 更新账户
export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';

// 班级活动列表
export const FETCH_CLASS_ACTIVITY_INFO_LIST = 'FETCH_CLASS_ACTIVITY_INFO_LIST';

// 班级活动详情
export const FETCH_CLASS_ACTIVITY_INFO_DETAIL = 'FETCH_CLASS_ACTIVITY_INFO_DETAIL';


